[package]
name = "code4fun"
version = "0.1.0"
authors = ["Stefan Kaestle <stefan.kaestle@oracle.com>"]
edition = "2018"

[dependencies]
regex = "1"
diesel = { version = "1.0.0", features = [ "mysql" ] }
dotenv = "0.9.0"